name: Go Automated Testing

on:
  push:
    branches: [ "main" ]

jobs:
  test-job:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./flashorder-go

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Set up Go environment
      uses: actions/setup-go@v5
      with:
        go-version: '1.23' 
        # 🌟 新增這行：明確告訴機器人 go.sum 在哪裡，消除警告！
        cache-dependency-path: flashorder-go/go.sum 

    - name: Install dependencies
      run: go mod download

    # 🌟 修改這行：我們目前只測試 service 資料夾 (不再用 ./... 盲目測全家)
    - name: Run Unit Tests
      run: go test -v ./service